---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2a
spec:
  securityGroups: 
    - sg-0fa43314947ae7981
  subnet: subnet-0bbc2fdc3c15009db
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-northeast-2c
spec:
  securityGroups: 
    - sg-0fa43314947ae7981
  subnet: subnet-02df2dd1a8a9fe4c3
